### ISSUE TITLE
crash with customnpcs ?

### ISSUE THREAD

**Issue by otakup0pe** [kreezxil/Localized-Chat#6]
On 1.12 with a customnpcs, localized chat, and a whole pile of other mods (listed [here](https://github.com/tribesthatmaybe/modpack/blob/59ae7fa1cb9ca36c9e7d6fcc8c6ce5640a252cdf/packmaker.yml)). 

```
[22:41:00] [Server thread/INFO] [STDOUT]: [com.kreezcraft.localizedchat.ChatListener:onChat:33]: I wonder how hot it gets in the day
[22:41:00] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.ServerChatEvent@289a1da:
java.lang.NullPointerException: null
        at com.kreezcraft.localizedchat.ChatListener.onChat(ChatListener.java:59) ~[ChatListener.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2101_ChatListener_onChat_ServerChatEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[LagGoggles-1.12.2-5.8-132.jar:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at noppes.npcs.entity.EntityNPCInterface.saySurrounding(EntityNPCInterface.java:949) [EntityNPCInterface.class:?]
        at noppes.npcs.ai.EntityAIWorldLines.func_75249_e(EntityAIWorldLines.java:27) [EntityAIWorldLines.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102) [xf.class:?]
        at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) [vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
        at noppes.npcs.entity.EntityNPCInterface.func_70636_d(EntityNPCInterface.java:425) [EntityNPCInterface.class:?]
        at net.minecraft.entity.EntityLivingBase.TickCentral_TrueOnUpdateTick(EntityLivingBase.java:2179) [vp.class:?]
        at net.minecraft.entity.EntityLiving.TickCentral_TrueOnUpdateTick(EntityLiving.java:295) [vq.class:?]
        at noppes.npcs.entity.EntityNPCInterface.TickCentral_TrueOnUpdateTick(EntityNPCInterface.java:297) [EntityNPCInterface.class:?]
        at noppes.npcs.entity.EntityCustomNpc.TickCentral_TrueOnUpdateTick(EntityCustomNpc.java:50) [EntityCustomNpc.class:?]
        at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56) [TickHub.class:?]
        at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:102) [LagGoggles-1.12.2-5.8-132.jar:?]
        at noppes.npcs.entity.EntityCustomNpc.func_70071_h_(EntityCustomNpc.java) [EntityCustomNpc.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1996) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1958) [amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1762) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by kreezxil** [comment]
that's not a whole pile of mods. For now you'll have to make a choice and
either remove localized chat or custom npcs. I'll let my programmer know
about this.

**Comment by otakup0pe** [comment]
Ha you are correct! [this](https://github.com/tribesthatmaybe/modpack/blob/59ae7fa1cb9ca36c9e7d6fcc8c6ce5640a252cdf/packmaker.yml) is a mostly complete list of the mods (i haven't pushed my local changes yet)

In the mean time I've pulled localized chat. Let me know what your dev says and if they need any more debug info! Thank you so much.

**Comment by kreezxil** [comment]
I've alerted him, he should be responding soon

**Comment by eleksploded** [comment]
Can you explain a way to replicate this crash please?

**Comment by otakup0pe** [comment]
I think the following _should_ work, if not I'll make a custom version of our pack for you to test with.

* install both customnpc and localized chat mods
* create a npc (using the npc wand, looks like a hoe)
* set it to have any "world" lines (advanced -> lines -> world I believe)
* wait until the npc tries talking

**Comment by eleksploded** [comment]
Update: I’ve identified what causes the crash, just a matter of figuring out how to fix it.

**Comment by eleksploded** [comment]
3.0.2 uploaded to curseforge
